service: ${self:custom.serverlessEnv.APP_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.serverlessEnv.STAGE}
  region: ${self:custom.serverlessEnv.REGION}
  environment:
    STAGE: ${self:custom.serverlessEnv.STAGE}

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 'lambda:InvokeFunction'
    Resource: "*"

functions:
  nuxt:
    warmup:
      enabled:
        - dev
    handler: index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.serverlessEnv.DOMAIN}
          ViewerCertificate:
            SslSupportMethod: sni-only
            AcmCertificateArn: 	arn:aws:acm:us-east-1:592854792012:certificate/048a6320-e34b-43b7-8102-dd3b69fd29ba
          Comment: nos-frontend CloudFront Distribution
          DefaultCacheBehavior:
            TargetOriginId: nosFrontendOrigin-${self:custom.serverlessEnv.STAGE}
            ViewerProtocolPolicy: 'redirect-to-https'
            DefaultTTL: 30
            ForwardedValues:
            # cloudfront에서 request header의 cookie중 어떤걸 오리진으로 넘겨줄지 설정하는 부분.
              Cookies:
                Forward: whitelist
                WhitelistedNames:
                  - nosJwt
              QueryString: false
          Enabled: true
          Origins:
            - Id: nosFrontendOrigin-${self:custom.serverlessEnv.STAGE}
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api.${self:custom.serverlessEnv.REGION}.amazonaws.com
              OriginPath: /${self:custom.serverlessEnv.STAGE}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only

plugins:
  - serverless-apigw-binary
  - serverless-plugin-warmup

custom:
  serverlessEnv: ${file(./config/serverless-env-loader.js)}
  warmup:
    prewarm: true
  apigwBinary:
    types:
      - '*/*'
