service: ${self:custom.serverlessEnv.APP_NAME}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.serverlessEnv.STAGE}
  region: ${self:custom.serverlessEnv.REGION}
  environment:
    STAGE: ${self:custom.serverlessEnv.STAGE}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  serverlessEnv: ${file(./config/serverless-env-loader.js)}
  apigwBinary:
    types:
      - '*/*'
  customDomain:
    domainName: ${self:custom.serverlessEnv.DOMAIN}
    basePath: ''
    stage: ${self:custom.serverlessEnv.STAGE}
    createRoute53Record: true