service: ${self:custom.serverlessEnv.APP_NAME}

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${self:custom.serverlessEnv.STAGE}
  region: ${self:custom.serverlessEnv.REGION}
  environment:
    STAGE: ${self:custom.serverlessEnv.STAGE}

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          ViewerCertificate:
            AcmCertificateArn: ${self:custom.serverlessEnv.CERTIFICATE_ARN}
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.1_2016
          Aliases:
            - ${self:custom.serverlessEnv.DOMAIN}
          Comment: nos-frontend CloudFront Distribution
          DefaultCacheBehavior:
            TargetOriginId: nosFrontendOrigin-${self:custom.serverlessEnv.STAGE}
            ViewerProtocolPolicy: 'redirect-to-https'
            ForwardedValues:
              QueryString: false
          Enabled: true
          Origins:
            - Id: nosFrontendOrigin
              DomainName:
                Fn::Join:
                  - "."
                  - - Ref: ApiGatewayRestApi
                    - execute-api.${self:custom.serverlessEnv.REGION}.amazonaws.com
              OriginPath: /${self:custom.serverlessEnv.STAGE}
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
    Route53RecordSet:
      Type: AWS::Route53::RecordSet
      Condition: willCreateRecordSet
      Properties:
        Type: A
        HostedZoneId: ${self:custom.serverlessEnv.HOSTED_ZONE_ID}
        Name: ${self:custom.serverlessEnv.DOMAIN}.
        AliasTarget:
          HostedZoneId: ${self:custom.serverlessEnv.HOSTED_ZONE_ID}
          DNSName:
            !GetAtt CloudFrontDistribution.DomainName


plugins:
  - serverless-apigw-binary
  - serverless-domain-manager

custom:
  serverlessEnv: ${file(./config/serverless-env-loader.js)}
  apigwBinary:
    types:
      - '*/*'
  # customDomain:
  #   domainName: ${self:custom.serverlessEnv.DOMAIN}
  #   basePath: ''
  #   stage: ${self:custom.serverlessEnv.STAGE}
  #   createRoute53Record: true